version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Maps host port 8000 to container port 8000
    volumes:
      - .:/app # Mounts the current directory to /app inside the container
    environment:
      NODE_ENV: production
    restart: unless-stopped
